title: Everlight Rental Co
description: Photo Booth and Event Rentals
theme: minima

show_pages_in_navigation: true
header_pages:
  - index.md
  - services.md
  - gallery.md
  - about.md
  - contact.md
  - booknow.md      # Book Now page

logo: /assets/logo.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag
